import os
from pathlib import Path

from dotenv import load_dotenv


load_dotenv(Path(__file__).with_name(".env"))


def env_bool(name, default="False"):
    return os.getenv(name, default).strip().lower() == "true"


def env_int(name, default):
    value = os.getenv(name)
    return int(value) if value not in (None, "") else default


def env_float(name, default):
    value = os.getenv(name)
    return float(value) if value not in (None, "") else default


def env_float_list(name, default):
    value = os.getenv(name)

    if value in (None, ""):
        return default

    result = []

    for item in value.split(","):
        item = item.strip()

        if item:
            result.append(float(item))

    return result or default


API_KEY = os.getenv("API_KEY")
SECRET_KEY = os.getenv("SECRET_KEY")

SYMBOLS = [
    symbol.strip()
    for symbol in os.getenv("SYMBOLS", "").split(",")
    if symbol.strip()
]

# Long-term mode: 1d trend, 4h confirmation, 1h entry timing.
TREND_TIMEFRAME = os.getenv("TREND_TIMEFRAME", "1d")
CONFIRMATION_TIMEFRAME = os.getenv("CONFIRMATION_TIMEFRAME", "4h")
ENTRY_TIMEFRAME = os.getenv("ENTRY_TIMEFRAME", "1h")
KLINE_LIMIT = env_int("KLINE_LIMIT", 300)
SCAN_SLEEP_SECONDS = env_int("SCAN_SLEEP_SECONDS", 900)
REQUEST_THROTTLE_SECONDS = env_float("REQUEST_THROTTLE_SECONDS", 0.08)
MAX_SCAN_SYMBOLS = env_int("MAX_SCAN_SYMBOLS", 0)
ENTRY_PRICE_RETRIES = env_int("ENTRY_PRICE_RETRIES", 8)
ENTRY_PRICE_RETRY_DELAY_SECONDS = env_float(
    "ENTRY_PRICE_RETRY_DELAY_SECONDS",
    0.25
)
PROTECTION_ORDER_DELAY_SECONDS = env_float(
    "PROTECTION_ORDER_DELAY_SECONDS",
    0.15
)
POST_TRADE_SLEEP_SECONDS = env_float("POST_TRADE_SLEEP_SECONDS", 0.25)

SIGNAL_JOURNAL_ENABLED = env_bool("SIGNAL_JOURNAL_ENABLED", "True")
SIGNAL_JOURNAL_PATH = os.getenv("SIGNAL_JOURNAL_PATH", "data/signal_journal.csv")
FUTURES_CONTEXT_ENABLED = env_bool("FUTURES_CONTEXT_ENABLED", "True")
FUTURES_CONTEXT_MIN_CONFIDENCE = env_float("FUTURES_CONTEXT_MIN_CONFIDENCE", 60)
FUTURES_CONTEXT_PERIOD = os.getenv("FUTURES_CONTEXT_PERIOD", "4h")
FUTURES_CONTEXT_LIMIT = env_int("FUTURES_CONTEXT_LIMIT", 8)
FUTURES_CONTEXT_CACHE_SECONDS = env_int("FUTURES_CONTEXT_CACHE_SECONDS", 900)
FUTURES_CONTEXT_MAX_SYMBOLS_PER_SCAN = env_int(
    "FUTURES_CONTEXT_MAX_SYMBOLS_PER_SCAN",
    12
)
FUTURES_CONTEXT_OI_MIN_CHANGE_PCT = env_float(
    "FUTURES_CONTEXT_OI_MIN_CHANGE_PCT",
    1.0
)
FUTURES_CONTEXT_TAKER_BUY_MIN = env_float("FUTURES_CONTEXT_TAKER_BUY_MIN", 1.05)
FUTURES_CONTEXT_TAKER_SELL_MAX = env_float("FUTURES_CONTEXT_TAKER_SELL_MAX", 0.95)
FUTURES_CONTEXT_CROWD_LONG_MAX = env_float(
    "FUTURES_CONTEXT_CROWD_LONG_MAX",
    2.2
)
FUTURES_CONTEXT_CROWD_SHORT_MIN = env_float(
    "FUTURES_CONTEXT_CROWD_SHORT_MIN",
    0.45
)
FUTURES_CONTEXT_FUNDING_ABS_MAX = env_float(
    "FUTURES_CONTEXT_FUNDING_ABS_MAX",
    0.001
)

SMC_ENABLED = env_bool("SMC_ENABLED", "True")
SMC_SWEEP_ENABLED = env_bool("SMC_SWEEP_ENABLED", "True")
SMC_OB_ENABLED = env_bool("SMC_OB_ENABLED", "True")
SMC_FVG_ENABLED = env_bool("SMC_FVG_ENABLED", "True")
SMC_SWEEP_LOOKBACK = env_int("SMC_SWEEP_LOOKBACK", 24)
SMC_SWEEP_MAX_AGE = env_int("SMC_SWEEP_MAX_AGE", 5)
SMC_OB_LOOKBACK = env_int("SMC_OB_LOOKBACK", 120)
SMC_OB_DISPLACEMENT_ATR = env_float("SMC_OB_DISPLACEMENT_ATR", 0.8)
SMC_OB_MAX_ZONE_PCT = env_float("SMC_OB_MAX_ZONE_PCT", 4.0)
SMC_FVG_LOOKBACK = env_int("SMC_FVG_LOOKBACK", 120)
SMC_FVG_MIN_GAP_ATR = env_float("SMC_FVG_MIN_GAP_ATR", 0.12)
SMC_TP_PATH_BLOCK_PENALTY = env_float("SMC_TP_PATH_BLOCK_PENALTY", 1.5)

LIVE_ENTRY_CONFIRMATION_ENABLED = env_bool("LIVE_ENTRY_CONFIRMATION_ENABLED", "True")
LIVE_ENTRY_FAST_TIMEFRAME = os.getenv("LIVE_ENTRY_FAST_TIMEFRAME", "5m")
LIVE_ENTRY_SLOW_TIMEFRAME = os.getenv("LIVE_ENTRY_SLOW_TIMEFRAME", "15m")
LIVE_ENTRY_KLINE_LIMIT = env_int("LIVE_ENTRY_KLINE_LIMIT", 80)
LIVE_ENTRY_REQUIRE_DATA = env_bool("LIVE_ENTRY_REQUIRE_DATA", "False")
LIVE_ENTRY_STRUCTURE_LOOKBACK = env_int("LIVE_ENTRY_STRUCTURE_LOOKBACK", 12)
LIVE_ENTRY_STRUCTURE_BUFFER_ATR = env_float("LIVE_ENTRY_STRUCTURE_BUFFER_ATR", 0.08)
LIVE_ENTRY_MIN_REVERSAL_BODY_ATR = env_float(
    "LIVE_ENTRY_MIN_REVERSAL_BODY_ATR",
    0.35
)
LIVE_ENTRY_REVERSAL_CLOSE_POSITION = env_float(
    "LIVE_ENTRY_REVERSAL_CLOSE_POSITION",
    0.30
)
MAX_LIVE_ENTRY_RETRACE_ATR = env_float("MAX_LIVE_ENTRY_RETRACE_ATR", 0.20)

LEVERAGE = env_int("LEVERAGE", 5)
MARGIN_TYPE = os.getenv("MARGIN_TYPE", "CROSSED").upper()
MARGIN_PER_TRADE = env_float("MARGIN_PER_TRADE", 5)

STATIC_TP_ENABLED = env_bool("STATIC_TP_ENABLED", "True")
STATIC_TP_ROI = env_float("STATIC_TP_ROI", env_float("ROI_PERCENT_TP", 6))
ROI_PERCENT_TP = env_float("ROI_PERCENT_TP", STATIC_TP_ROI)
STRUCTURE_TP_MIN_ROI = env_float("STRUCTURE_TP_MIN_ROI", 8)
STRUCTURE_TP_MAX_ROI = env_float("STRUCTURE_TP_MAX_ROI", 120)
STRUCTURE_TP_MIN_SCORE = env_float("STRUCTURE_TP_MIN_SCORE", 2.0)
STRUCTURE_TP_BUFFER_PCT = env_float("STRUCTURE_TP_BUFFER_PCT", 0.15)
STRUCTURE_TP_ATR_BUFFER_MULT = env_float("STRUCTURE_TP_ATR_BUFFER_MULT", 0.25)
STRUCTURE_TP_FALLBACK_ROI = env_float("STRUCTURE_TP_FALLBACK_ROI", ROI_PERCENT_TP)
ENTRY_TP_ROOM_CHECK_ENABLED = env_bool("ENTRY_TP_ROOM_CHECK_ENABLED", "True")
ENTRY_MIN_TP_ROOM_ROI = env_float("ENTRY_MIN_TP_ROOM_ROI", STRUCTURE_TP_MIN_ROI)
ENTRY_TP_ROOM_MIN_LEVEL_SCORE = env_float(
    "ENTRY_TP_ROOM_MIN_LEVEL_SCORE",
    STRUCTURE_TP_MIN_SCORE
)
ENTRY_TP_ROOM_BLOCK_IF_NO_LEVEL = env_bool(
    "ENTRY_TP_ROOM_BLOCK_IF_NO_LEVEL",
    "False"
)

DCA_ENABLED = env_bool("DCA_ENABLED", "False")
DCA_MANAGE_EXISTING_POSITIONS = env_bool("DCA_MANAGE_EXISTING_POSITIONS", "False")
DCA_STATE_PATH = os.getenv("DCA_STATE_PATH", "data/open_trades.json")
DCA_MAX_ORDERS = env_int("DCA_MAX_ORDERS", 2)
DCA_INITIAL_MARGIN_PCT = env_float("DCA_INITIAL_MARGIN_PCT", 50)
DCA_MARGIN_PCTS = env_float_list("DCA_MARGIN_PCTS", [30, 20])
DCA_TRIGGER_ROIS = env_float_list("DCA_TRIGGER_ROIS", [15, 30])
DCA_MAX_ADVERSE_ROI = env_float("DCA_MAX_ADVERSE_ROI", 45)
DCA_MIN_SECONDS_BETWEEN_ORDERS = env_int("DCA_MIN_SECONDS_BETWEEN_ORDERS", 3600)
DCA_MIN_PRICE_GAP_ROI = env_float("DCA_MIN_PRICE_GAP_ROI", 8)
DCA_REQUIRE_TREND_CONFIRMATION = env_bool("DCA_REQUIRE_TREND_CONFIRMATION", "True")
DCA_REPRICE_TP_AFTER_FILL = env_bool("DCA_REPRICE_TP_AFTER_FILL", "True")
DCA_STRUCTURE_LEVEL_ENABLED = env_bool("DCA_STRUCTURE_LEVEL_ENABLED", "True")
DCA_STRUCTURE_MIN_SCORE = env_float("DCA_STRUCTURE_MIN_SCORE", 2.0)
DCA_STRUCTURE_MAX_DISTANCE_ATR = env_float("DCA_STRUCTURE_MAX_DISTANCE_ATR", 0.6)
DCA_STRUCTURE_MAX_DISTANCE_ROI = env_float("DCA_STRUCTURE_MAX_DISTANCE_ROI", 6)
DCA_STRUCTURE_REQUIRE_REACTION = env_bool("DCA_STRUCTURE_REQUIRE_REACTION", "True")
DCA_STRUCTURE_REACTION_LOOKBACK = env_int("DCA_STRUCTURE_REACTION_LOOKBACK", 3)
DCA_STRUCTURE_REACTION_MIN_BODY_ATR = env_float(
    "DCA_STRUCTURE_REACTION_MIN_BODY_ATR",
    0.05
)
DCA_STRUCTURE_REACTION_CLOSE_POSITION = env_float(
    "DCA_STRUCTURE_REACTION_CLOSE_POSITION",
    0.55
)

# Default long-term behavior is no exchange SL. The adverse-zone support or
# resistance check is used for trade quality, not as a mandatory stop order.
SL_ENABLED = env_bool("SL_ENABLED", "False")
MAX_SL_ROI = env_float("MAX_SL_ROI", 50)

LONG_TERM_SIGNAL_THRESHOLD = env_float("LONG_TERM_SIGNAL_THRESHOLD", 72)
LONG_TERM_MIN_SIGNAL_EDGE = env_float("LONG_TERM_MIN_SIGNAL_EDGE", 5)
LONG_TERM_MAX_ADVERSE_ROI = env_float("LONG_TERM_MAX_ADVERSE_ROI", 50)
LONG_TERM_SR_LOOKBACK = env_int("LONG_TERM_SR_LOOKBACK", 160)
LONG_TERM_SR_MIN_TOUCHES = env_int("LONG_TERM_SR_MIN_TOUCHES", 2)
LONG_TERM_SR_MIN_SCORE = env_float("LONG_TERM_SR_MIN_SCORE", 2.5)
LONG_TERM_SR_TOLERANCE_PCT = env_float("LONG_TERM_SR_TOLERANCE_PCT", 1.0)
LONG_TERM_SR_ATR_TOLERANCE = env_float("LONG_TERM_SR_ATR_TOLERANCE", 0.75)
LONG_TERM_ENTRY_MAX_EMA_DISTANCE_PCT = env_float(
    "LONG_TERM_ENTRY_MAX_EMA_DISTANCE_PCT",
    6.0
)
LONG_TERM_MIN_ADX = env_float("LONG_TERM_MIN_ADX", 14)
LONG_TERM_BTC_CORR_THRESHOLD = env_float("LONG_TERM_BTC_CORR_THRESHOLD", 0.65)

MAX_TOTAL_POSITIONS = (
    int(os.getenv("MAX_TOTAL_POSITIONS"))
    if os.getenv("MAX_TOTAL_POSITIONS")
    else None
)

MAX_BUY_POSITIONS = (
    int(os.getenv("MAX_BUY_POSITIONS"))
    if os.getenv("MAX_BUY_POSITIONS")
    else None
)

MAX_SELL_POSITIONS = (
    int(os.getenv("MAX_SELL_POSITIONS"))
    if os.getenv("MAX_SELL_POSITIONS")
    else None
)

TESTNET = env_bool("TESTNET", "False")
